language: c++
os:
  - linux
compiler:
  - gcc
before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get update -qq && sudo apt-get install -qq libgl1-mesa-dev freeglut3-dev mesa-common-dev
    fi
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make RunTests
  - make test
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
