language: c++
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make RunTests
  - ./RunTests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libgl1-mesa-dev
      - freeglut3-dev 
      - mesa-common-dev
    update: true
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - CC=gcc-7 
        - CXX=g++-7
    - os: linux
      compiler: clang
    - os: windows
      language: cpp
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - MSBuild.exe PerfectPixel.sln
        - ./Debug/RunTests.exe
