#pragma once

#ifdef PP_FULL_REFLECTION
#define PP_FULL_REFLECTION_ENABLED 1
#else
#define PP_FULL_REFLECTION_ENABLED 0
#endif

#ifdef PP_CLEANUP_CALLBACKS
#define PP_CLEANUP_CALLBACKS_ENABLED 1
#else
#define PP_CLEANUP_CALLBACKS_ENABLED 0
#endif

#define PP_TICK_WRAP_PROTECTION_ENABLED 1
